apiVersion: v1
kind: Pod

metadata:
  name: flask-pod
  namespace: flask-app
spec:
  containers:
    - name: flask-app
      image: nikhilhadawale/flask_todo_app:latest
      ports:
      - containerPort: 5000
    - name: my-container
      image: nginx:latest
      ports:
        - containerPort: 80
